# Generated by Django 2.2.2 on 2019-07-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0037_auto_20190727_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadScheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.PositiveIntegerField()),
                ('hasta', models.PositiveIntegerField()),
                ('prioridad', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioridades', to='elecciones.Categoria')),
                ('circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioridades', to='elecciones.Circuito')),
            ],
        ),
    ]
