# Generated by Django 2.2.2 on 2019-08-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioridadscheduling',
            name='prioridad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
