# Generated by Django 2.2.2 on 2019-09-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0057_auto_20190901_1444'),
        ('scheduling', '0003_colacargapendientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='colacargapendientes',
            name='numero_carga',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='colacargapendientes',
            unique_together={('mesaCategoria', 'numero_carga')},
        ),
    ]
