# Generated by Django 2.2.2 on 2019-09-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0059_merge_20190910_0847'),
        ('scheduling', '0003_colacargapendientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaCargasPendientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True)),
                ('mesa_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.MesaCategoria')),
            ],
        ),
        migrations.DeleteModel(
            name='ColaCargaPendientes',
        ),
    ]
