# Generated by Django 2.2.2 on 2019-09-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0014_reemplazo_taken'),
        ('scheduling', '0003_asignacion_batch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colacargaspendientes',
            unique_together={('attachment', 'numero_carga')},
        ),
    ]
