# Generated by Django 2.2.2 on 2019-10-01 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0061_carga_tomada_por_consolidador'),
        ('scheduling', '0003_asignacion_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='colacargaspendientes',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.Distrito'),
        ),
        migrations.AddIndex(
            model_name='colacargaspendientes',
            index=models.Index(fields=['distrito', 'orden'], name='orden_distrito'),
        ),
    ]
