# Generated by Django 2.2.2 on 2019-09-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0059_merge_20190910_0847'),
        ('adjuntos', '0014_reemplazo_taken'),
        ('scheduling', '0004_auto_20190922_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colacargaspendientes',
            options={'verbose_name': 'Cola de Identificaciones y Cargas pendientes', 'verbose_name_plural': 'Cola de Identificaciones y Cargas pendientes'},
        ),
        migrations.AlterUniqueTogether(
            name='colacargaspendientes',
            unique_together={('attachment', 'numero_carga'), ('mesa_categoria', 'numero_carga')},
        ),
    ]
