# Generated by Django 2.2.2 on 2019-09-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0059_merge_20190910_0847'),
        ('scheduling', '0004_auto_20190910_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colacargapendientes',
            old_name='mesaCategoria',
            new_name='mesa_categoria',
        ),
        migrations.AlterUniqueTogether(
            name='colacargapendientes',
            unique_together={('mesa_categoria', 'numero_carga')},
        ),
    ]
