# Generated by Django 2.2.2 on 2019-10-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0061_carga_tomada_por_consolidador'),
        ('scheduling', '0004_colacargaspendientes_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='colacargaspendientes',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.Seccion'),
        ),
        migrations.AddIndex(
            model_name='colacargaspendientes',
            index=models.Index(fields=['seccion', 'orden'], name='orden_seccion'),
        ),
    ]
