# Generated by Django 2.2.2 on 2019-09-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0059_merge_20190910_0847'),
        ('scheduling', '0005_auto_20190915_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColaCargaPendientes',
            new_name='ColaCargasPendientes',
        ),
    ]
