# Generated by Django 2.2.2 on 2019-09-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_auto_20190916_0031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colacargaspendientes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='colacargaspendientes',
            name='carga_parcial',
        ),
        migrations.RemoveField(
            model_name='colacargaspendientes',
            name='numero_carga',
        ),
    ]
