dist: xenial
language: python
python:
  - "3.9"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -y
  - sudo apt-get install -y gdal-bin
  - sudo apt-get install -y poppler-utils

services:
  - postgresql

pip:
  - pip install -r requirements.txt

script:
  - pytest

after_success:
  - coveralls

env:
  - PGPORT=5432 DJANGO_SECRET_KEY="hard to guess string"
