import pytest
from django.core.management import call_command
from .test_resultados import fiscal_client
from .factories import VotoMesaReportadoFactory
from elecciones.models import Mesa, Opcion, VotoMesaReportado


@pytest.fixture
def carta_marina_oficial(django_db_setup, django_db_blocker):
    with django_db_blocker.unblock():
        call_command('loaddata', 'fixtures/neuquen.json')


def m(num):
    return Mesa.objects.get(numero=num)


def o(num_o_nombre):
    if num_o_nombre.isdigit():
        return Opcion.objects.get(codigo_dne=num_o_nombre)
    else:
        return Opcion.objects.get(nombre_corto__iexact=num_o_nombre)


def test_proyeccion(fiscal_client, carta_marina_oficial):
    VotoMesaReportado.objects.all().delete()
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(42), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(57), votos=4)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(29), votos=4)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(91), votos=3)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(21), votos=4)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(51), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(124), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(10), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(133), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(36), votos=6)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(85), votos=2)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(43), votos=2)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(5), votos=2)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(24), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(93), votos=6)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(99), votos=9)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(102), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(36), votos=6)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(61), votos=4)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(41), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(25), votos=2)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(20), votos=2)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(21), votos=3)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(21), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(27), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(11), votos=4)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(14), votos=3)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(16), votos=7)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(43), votos=5)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(87), votos=4)
    VotoMesaReportadoFactory(opcion=o("23"), mesa=m(36), votos=4)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(42), votos=9)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(57), votos=10)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(29), votos=9)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(91), votos=7)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(21), votos=11)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(51), votos=11)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(124), votos=15)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(10), votos=14)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(133), votos=14)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(36), votos=11)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(85), votos=4)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(43), votos=5)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(5), votos=2)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(24), votos=5)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(93), votos=10)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(99), votos=11)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(102), votos=5)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(36), votos=8)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(61), votos=5)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(41), votos=6)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(25), votos=3)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(20), votos=4)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(21), votos=7)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(21), votos=5)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(27), votos=6)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(11), votos=2)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(14), votos=2)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(16), votos=4)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(43), votos=6)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(87), votos=7)
    VotoMesaReportadoFactory(opcion=o("40"), mesa=m(36), votos=5)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(42), votos=4)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(57), votos=7)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(29), votos=6)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(91), votos=4)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(21), votos=5)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(51), votos=5)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(124), votos=6)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(10), votos=5)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(133), votos=5)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(36), votos=4)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(85), votos=2)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(43), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(5), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(24), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(93), votos=5)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(99), votos=5)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(102), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(36), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(61), votos=4)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(41), votos=4)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(25), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(20), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(21), votos=4)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(21), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(27), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(11), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(14), votos=4)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(16), votos=3)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(43), votos=4)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(87), votos=6)
    VotoMesaReportadoFactory(opcion=o("68"), mesa=m(36), votos=5)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(42), votos=44)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(57), votos=46)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(29), votos=45)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(91), votos=32)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(21), votos=37)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(51), votos=48)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(124), votos=55)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(10), votos=69)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(133), votos=69)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(36), votos=69)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(85), votos=30)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(43), votos=44)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(5), votos=118)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(24), votos=65)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(93), votos=35)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(99), votos=39)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(102), votos=79)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(36), votos=52)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(61), votos=97)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(41), votos=83)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(25), votos=115)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(20), votos=119)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(21), votos=100)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(21), votos=71)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(27), votos=84)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(11), votos=93)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(14), votos=107)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(16), votos=83)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(43), votos=72)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(87), votos=30)
    VotoMesaReportadoFactory(opcion=o("151"), mesa=m(36), votos=43)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(42), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(57), votos=4)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(29), votos=4)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(91), votos=3)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(21), votos=4)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(51), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(124), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(10), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(133), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(36), votos=6)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(85), votos=2)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(43), votos=2)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(5), votos=2)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(24), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(93), votos=6)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(99), votos=9)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(102), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(36), votos=6)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(61), votos=4)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(41), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(25), votos=2)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(20), votos=2)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(21), votos=3)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(21), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(27), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(11), votos=4)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(14), votos=3)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(16), votos=7)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(43), votos=5)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(87), votos=4)
    VotoMesaReportadoFactory(opcion=o("189"), mesa=m(36), votos=4)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(42), votos=61)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(57), votos=72)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(29), votos=78)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(91), votos=100)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(21), votos=94)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(51), votos=66)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(124), votos=54)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(10), votos=37)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(133), votos=45)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(36), votos=43)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(85), votos=28)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(43), votos=34)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(5), votos=47)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(24), votos=44)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(93), votos=59)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(99), votos=55)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(102), votos=43)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(36), votos=28)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(61), votos=39)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(41), votos=35)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(25), votos=17)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(20), votos=19)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(21), votos=26)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(21), votos=43)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(27), votos=36)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(11), votos=10)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(14), votos=21)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(16), votos=28)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(43), votos=46)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(87), votos=81)
    VotoMesaReportadoFactory(opcion=o("651"), mesa=m(36), votos=75)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(42), votos=64)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(57), votos=50)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(29), votos=48)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(91), votos=35)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(21), votos=41)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(51), votos=62)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(124), votos=69)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(10), votos=65)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(133), votos=74)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(36), votos=80)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(85), votos=184)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(43), votos=155)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(5), votos=30)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(24), votos=95)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(93), votos=94)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(99), votos=76)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(102), votos=89)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(36), votos=89)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(61), votos=65)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(41), votos=77)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(25), votos=93)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(20), votos=76)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(21), votos=86)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(21), votos=88)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(27), votos=66)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(11), votos=55)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(14), votos=100)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(16), votos=83)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(43), votos=72)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(87), votos=51)
    VotoMesaReportadoFactory(opcion=o("652"), mesa=m(36), votos=40)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(42), votos=19)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(57), votos=19)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(29), votos=18)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(91), votos=14)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(21), votos=22)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(51), votos=22)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(124), votos=24)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(10), votos=35)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(133), votos=23)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(36), votos=19)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(85), votos=9)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(43), votos=8)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(5), votos=7)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(24), votos=16)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(93), votos=18)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(99), votos=21)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(102), votos=10)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(36), votos=11)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(61), votos=6)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(41), votos=11)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(25), votos=8)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(20), votos=5)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(21), votos=12)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(21), votos=4)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(27), votos=8)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(11), votos=4)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(14), votos=5)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(16), votos=8)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(43), votos=10)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(87), votos=15)
    VotoMesaReportadoFactory(opcion=o("653"), mesa=m(36), votos=10)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(42), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(57), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(29), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(91), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(21), votos=1)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(51), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(124), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(10), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(133), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(36), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(85), votos=1)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(43), votos=1)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(5), votos=1)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(24), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(93), votos=4)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(99), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(102), votos=1)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(36), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(61), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(41), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(25), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(20), votos=1)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(21), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(21), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(27), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(11), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(14), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(16), votos=3)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(43), votos=2)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(87), votos=3)
    VotoMesaReportadoFactory(opcion=o("842"), mesa=m(36), votos=2)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(42), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(57), votos=4)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(29), votos=4)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(91), votos=3)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(21), votos=4)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(51), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(124), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(10), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(133), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(36), votos=6)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(85), votos=2)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(43), votos=2)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(5), votos=2)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(24), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(93), votos=6)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(99), votos=9)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(102), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(36), votos=6)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(61), votos=4)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(41), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(25), votos=2)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(20), votos=2)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(21), votos=3)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(21), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(27), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(11), votos=4)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(14), votos=3)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(16), votos=7)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(43), votos=5)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(87), votos=4)
    VotoMesaReportadoFactory(opcion=o("863"), mesa=m(36), votos=4)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(42), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(57), votos=4)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(29), votos=4)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(91), votos=3)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(21), votos=4)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(51), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(124), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(10), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(133), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(36), votos=6)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(85), votos=2)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(43), votos=2)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(5), votos=2)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(24), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(93), votos=6)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(99), votos=9)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(102), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(36), votos=6)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(61), votos=4)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(41), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(25), votos=2)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(20), votos=2)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(21), votos=3)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(21), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(27), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(11), votos=4)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(14), votos=3)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(16), votos=7)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(43), votos=5)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(87), votos=4)
    VotoMesaReportadoFactory(opcion=o("882"), mesa=m(36), votos=4)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(42), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(57), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(29), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(91), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(21), votos=1)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(51), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(124), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(10), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(133), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(36), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(85), votos=1)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(43), votos=1)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(5), votos=1)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(24), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(93), votos=4)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(99), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(102), votos=1)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(36), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(61), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(41), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(25), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(20), votos=1)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(21), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(21), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(27), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(11), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(14), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(16), votos=3)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(43), votos=2)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(87), votos=3)
    VotoMesaReportadoFactory(opcion=o("883"), mesa=m(36), votos=2)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(42), votos=9)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(57), votos=8)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(29), votos=7)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(91), votos=5)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(21), votos=5)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(51), votos=8)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(124), votos=9)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(10), votos=11)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(133), votos=9)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(36), votos=7)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(85), votos=10)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(43), votos=8)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(5), votos=6)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(24), votos=12)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(93), votos=10)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(99), votos=15)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(102), votos=11)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(36), votos=17)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(61), votos=12)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(41), votos=13)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(25), votos=13)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(20), votos=10)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(21), votos=15)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(21), votos=11)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(27), votos=12)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(11), votos=6)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(14), votos=8)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(16), votos=11)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(43), votos=14)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(87), votos=15)
    VotoMesaReportadoFactory(opcion=o("BLANCO"), mesa=m(36), votos=13)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(42), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(57), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(29), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(91), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(21), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(51), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(124), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(10), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(133), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(36), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(85), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(43), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(5), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(24), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(93), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(99), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(102), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(36), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(61), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(41), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(25), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(20), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(21), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(21), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(27), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(11), votos=1)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(14), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(16), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(43), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(87), votos=0)
    VotoMesaReportadoFactory(opcion=o("IMPUGNADOS"), mesa=m(36), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(42), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(57), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(29), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(91), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(21), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(51), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(124), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(10), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(133), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(36), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(85), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(43), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(5), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(24), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(93), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(99), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(102), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(36), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(61), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(41), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(25), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(20), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(21), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(21), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(27), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(11), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(14), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(16), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(43), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(87), votos=0)
    VotoMesaReportadoFactory(opcion=o("Recurridos"), mesa=m(36), votos=0)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(42), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(57), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(29), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(91), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(21), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(51), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(124), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(10), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(133), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(36), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(85), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(43), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(5), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(24), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(93), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(99), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(102), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(36), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(61), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(41), votos=0)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(25), votos=0)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(20), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(21), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(21), votos=0)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(27), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(11), votos=1)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(14), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(16), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(43), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(87), votos=2)
    VotoMesaReportadoFactory(opcion=o("Observados"), mesa=m(36), votos=1)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(42), votos=261)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(57), votos=262)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(29), votos=264)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(91), votos=254)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(21), votos=273)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(51), votos=274)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(124), votos=280)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(10), votos=276)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(133), votos=283)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(36), votos=279)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(85), votos=290)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(43), votos=281)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(5), votos=244)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(24), votos=283)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(93), votos=289)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(99), votos=285)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(102), votos=281)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(36), votos=248)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(61), votos=266)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(41), votos=267)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(25), votos=271)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(20), votos=256)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(21), votos=278)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(21), votos=266)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(27), votos=254)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(11), votos=199)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(14), votos=273)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(16), votos=267)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(43), votos=268)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(87), votos=262)
    VotoMesaReportadoFactory(opcion=o("Total"), mesa=m(36), votos=242)

    resultados = fiscal_client.get('/elecciones/resultados/?proyectado=1').context['resultados']
    resultados_pk = fiscal_client.get('/elecciones/resultadospk/?proyectado=1').context['resultados']

    # ver data completa en https://gist.github.com/mgaitan/289aa9a7dcaf3d28efe38fb6e0c32d48

    tabla_positivos = list(resultados['tabla_positivos'].items())

    partido, fila = tabla_positivos[0]        #
    assert partido.nombre == 'Movimiento Popular Neuquino y Otros - Gutiérrez'
    assert fila['proyeccion'] == '31.75'

    partido, fila = tabla_positivos[1]        #
    assert partido.nombre == 'Unidad Ciudadana Frente Neuquino - Rioseco'
    assert fila['proyeccion'] == '28.65'

    partido, fila = tabla_positivos[2]
    assert partido.nombre == 'Cambiemos - Quiroga'
    assert fila['proyeccion'] == '24.90'

    # pk
    tabla_positivos = list(resultados_pk['tabla_positivos'].items())

    partido, fila = tabla_positivos[0]        #
    assert partido.nombre == 'Movimiento Popular Neuquino y Otros - Gutiérrez'
    assert fila['proyeccion'] == '31.75'

    partido, fila = tabla_positivos[1]        #
    assert partido.nombre == 'Unidad Ciudadana Frente Neuquino - Rioseco'
    assert fila['proyeccion'] == '28.65'

    partido, fila = tabla_positivos[2]
    assert partido.nombre == 'Cambiemos - Quiroga'
    assert fila['proyeccion'] == '24.90'





