# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionFiscalDeMesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ingreso', models.DateTimeField(editable=False, null=True)),
                ('egreso', models.DateTimeField(editable=False, null=True)),
                ('comida', models.CharField(choices=[('no asignada', 'no asignada'), ('asignada', 'asignada'), ('recibida', 'recibida')], default='no asignada', max_length=50)),
            ],
            options={
                'verbose_name': 'Asignación de Fiscal de Mesa',
                'verbose_name_plural': 'Asignaciones de Fiscal de Mesa',
            },
        ),
        migrations.CreateModel(
            name='AsignacionFiscalGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ingreso', models.DateTimeField(editable=False, null=True)),
                ('egreso', models.DateTimeField(editable=False, null=True)),
                ('comida', models.CharField(choices=[('no asignada', 'no asignada'), ('asignada', 'asignada'), ('recibida', 'recibida')], default='no asignada', max_length=50)),
                ('eleccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Eleccion')),
            ],
            options={
                'verbose_name': 'Asignación de Fiscal General',
                'verbose_name_plural': 'Asignaciones de Fiscal General',
            },
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', model_utils.fields.StatusField(choices=[('IMPORTADO', 'IMPORTADO'), ('AUTOCONFIRMADO', 'AUTOCONFIRMADO'), ('PRE-INSCRIPTO', 'PRE-INSCRIPTO'), ('CONFIRMADO', 'CONFIRMADO'), ('DECLINADO', 'DECLINADO')], default='PRE-INSCRIPTO', max_length=100, no_check_for_status=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas, no se muestran')),
                ('disponibilidad', models.CharField(blank=True, choices=[('mañana', 'mañana'), ('tarde', 'tarde'), ('todo el día', 'todo el día')], max_length=20)),
                ('movilidad', models.NullBooleanField(help_text='Movilidad propia')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('de_mesa', 'de Mesa')], max_length=20)),
                ('codigo_confirmacion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email_confirmado', models.BooleanField(default=False)),
                ('apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('barrio', models.CharField(blank=True, max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=200)),
                ('tipo_dni', models.CharField(choices=[('DNI', 'DNI'), ('CI', 'CI'), ('LE', 'LE'), ('LC', 'LC')], default='DNI', max_length=3)),
                ('dni', models.CharField(blank=True, max_length=15, null=True)),
                ('escuela_donde_vota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.LugarVotacion', verbose_name='Escuela preferida para fiscalizar')),
            ],
            options={
                'verbose_name_plural': 'Fiscales',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('referentes', models.ManyToManyField(blank=True, related_name='es_referente_de_orga', to='fiscales.Fiscal')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.AddField(
            model_name='fiscal',
            name='organizacion',
            field=models.ForeignKey(blank=True, help_text='Opcional. Para mostrar contactos extra del usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscales.Organizacion'),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacionfiscalgeneral',
            name='fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_escuela', to='fiscales.Fiscal'),
        ),
        migrations.AddField(
            model_name='asignacionfiscalgeneral',
            name='lugar_votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='elecciones.LugarVotacion'),
        ),
        migrations.AddField(
            model_name='asignacionfiscaldemesa',
            name='fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_mesa', to='fiscales.Fiscal'),
        ),
        migrations.AddField(
            model_name='asignacionfiscaldemesa',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='elecciones.Mesa'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscal',
            unique_together=set([('tipo_dni', 'dni')]),
        ),
    ]
