# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-04 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionfiscaldemesa',
            name='fiscal',
        ),
        migrations.RemoveField(
            model_name='asignacionfiscaldemesa',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='asignacionfiscalgeneral',
            name='eleccion',
        ),
        migrations.RemoveField(
            model_name='asignacionfiscalgeneral',
            name='fiscal',
        ),
        migrations.RemoveField(
            model_name='asignacionfiscalgeneral',
            name='lugar_votacion',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='referentes',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='escuela_donde_vota',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='movilidad',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='AsignacionFiscalDeMesa',
        ),
        migrations.DeleteModel(
            name='AsignacionFiscalGeneral',
        ),
        migrations.DeleteModel(
            name='Organizacion',
        ),
    ]
