# Generated by Django 2.2.2 on 2019-07-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0002_auto_20190504_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='troll',
            field=models.BooleanField(default=False),
        ),
    ]
