# Generated by Django 2.2.2 on 2019-07-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0003_auto_20190723_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='referido_codigo',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fiscal',
            name='referido_por_codigo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
