# Generated by Django 2.2.2 on 2019-07-24 22:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0003_auto_20190723_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='referido_codigo',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
