# Generated by Django 2.2.2 on 2019-07-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0004_auto_20190723_2205'),
        ('fiscales', '0004_auto_20190724_1944'),
    ]

    operations = [
    ]
