# Generated by Django 2.2.2 on 2019-07-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0004_auto_20190724_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='referido_por_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
