# Generated by Django 2.2.2 on 2019-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0004_auto_20190724_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='referido_codigo',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
