# Generated by Django 2.2.2 on 2019-07-28 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


def crear_codigo(apps, schema_editor):
    Fiscal = apps.get_model("fiscales", "Fiscal")
    CodigoReferido = apps.get_model("fiscales", "CodigoReferido")
    for i, f in enumerate(Fiscal.objects.all()):
        CodigoReferido.objects.create(fiscal=f, codigo=f'{i:04}')


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0004_auto_20190727_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscal',
            name='referido_codigo',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='referido_por_apellido',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='referido_por_codigo',
        ),
        migrations.RemoveField(
            model_name='fiscal',
            name='referido_por_nombres',
        ),
        migrations.AddField(
            model_name='fiscal',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.Fiscal'),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='referente_apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='referente_certeza',
            field=models.PositiveIntegerField(default=100, help_text='El código no era exacto?'),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='referente_nombres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='referido_por_codigos',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='CodigoReferido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(help_text='Código con el que el fiscal puede referir a otres', max_length=4, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_de_referidos', to='fiscales.Fiscal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(crear_codigo),
    ]
