# Generated by Django 2.2.2 on 2019-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0004_auto_20190727_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='last_seen',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
