# Generated by Django 2.2.2 on 2019-07-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0005_auto_20190728_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='referencia_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fiscal',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='fiscales.Fiscal'),
        ),
    ]
