# Generated by Django 2.2.2 on 2019-08-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0041_categoria_sensible'),
        ('fiscales', '0005_auto_20190728_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal', to='elecciones.Distrito'),
        ),
    ]
