# Generated by Django 2.2.2 on 2019-08-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0005_prevenir_doble_logueo'),
        ('fiscales', '0006_distrito_en_fiscal'),
    ]

    operations = [
    ]
