# Generated by Django 2.2.2 on 2019-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0008_auto_20190807_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='ingreso_alguna_vez',
            field=models.BooleanField(default=False),
        ),
    ]
