# Generated by Django 2.2.2 on 2019-08-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0009_ingreso_alguna_vez'),
    ]

    operations = [
    ]
