# Generated by Django 2.2.2 on 2019-08-14 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0055_reemplazo_taken'),
        ('adjuntos', '0014_reemplazo_taken'),
        ('fiscales', '0010_saneamiento_correos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='attachment_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_asignado', to='adjuntos.Attachment'),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='mesa_categoria_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_asignado', to='elecciones.MesaCategoria'),
        ),
    ]
