# Generated by Django 2.2.2 on 2019-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0011_reemplazo_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='puntaje_scoring_troll',
            field=models.IntegerField(default=0),
        ),
    ]
