# Generated by Django 2.2.2 on 2019-10-01 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0061_carga_tomada_por_consolidador'),
        ('fiscales', '0012_fiscal_puntaje_scoring_troll'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='distrito_afin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_afin', to='elecciones.Distrito'),
        ),
    ]
