# Generated by Django 2.2.2 on 2019-09-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0012_tarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
