# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import djgeojson.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgrupacionPK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad_cabecera', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Circuito electoral',
                'verbose_name_plural': 'Circuitos electorales',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Elección',
                'verbose_name_plural': 'Elecciones',
            },
        ),
        migrations.CreateModel(
            name='LugarVotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('calidad', models.CharField(blank=True, editable=False, help_text='calidad de la geolocalizacion', max_length=20)),
                ('electores', models.PositiveIntegerField(blank=True, null=True)),
                ('geom', djgeojson.fields.PointField(null=True)),
                ('latitud', models.FloatField(editable=False, null=True)),
                ('longitud', models.FloatField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Lugar de votación',
                'verbose_name_plural': 'Lugares de votación',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', model_utils.fields.StatusField(choices=[('EN ESPERA', 'EN ESPERA'), ('ABIERTA', 'ABIERTA'), ('CERRADA', 'CERRADA'), ('ESCRUTADA', 'ESCRUTADA')], default='EN ESPERA', max_length=100, no_check_for_status=True)),
                ('hora_abierta', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='estado', when=set(['ABIERTA']))),
                ('hora_cerrada', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='estado', when=set(['CERRADA']))),
                ('hora_escrutada', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='estado', when=set(['ESCRUTADA']))),
                ('numero', models.PositiveIntegerField()),
                ('es_testigo', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, help_text='url al telegrama')),
                ('electores', models.PositiveIntegerField(blank=True, null=True)),
                ('taken', models.DateTimeField(editable=False, null=True)),
                ('orden_de_carga', models.PositiveIntegerField(default=0, editable=False)),
                ('carga_confirmada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(default='', max_length=10)),
                ('orden', models.PositiveIntegerField(blank=True, help_text='Orden en la boleta', null=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('es_contable', models.BooleanField(default=True)),
                ('codigo_dne', models.PositiveIntegerField(blank=True, help_text='Nº asignado en la base de datos de resultados oficiales', null=True)),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Orden opcion')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(default='', max_length=30)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('referencia', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(null=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sección electoral',
                'verbose_name_plural': 'Secciones electorales',
            },
        ),
        migrations.CreateModel(
            name='VotoMesaReportado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('votos', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
