# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-03 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0002_auto_20190501_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='hora_abierta',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='hora_cerrada',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='eleccion',
        ),
        migrations.AddField(
            model_name='mesa',
            name='eleccion',
            field=models.ManyToManyField(to='elecciones.Eleccion'),
        ),
    ]
