# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-04 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_auto_20190503_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='votomesareportado',
            name='eleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Eleccion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            unique_together=set([('mesa', 'eleccion', 'opcion')]),
        ),
    ]
