# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0004_auto_20190503_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
