# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-04 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0005_auto_20190504_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuito',
            name='referentes',
        ),
    ]
