# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0005_auto_20190504_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='codigo',
            field=models.CharField(blank=True, help_text='Codigo de partido', max_length=10, null=True),
        ),
    ]
