# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0006_remove_circuito_referentes'),
        ('elecciones', '0006_partido_codigo'),
    ]

    operations = [
    ]
