# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0007_merge_20190505_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarvotacion',
            name='estado_geolocalizacion',
            field=models.PositiveIntegerField(default=0, help_text='Indicador (0-10) de que confianza hay en la geolozalización'),
        ),
    ]
