# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0009_auto_20190505_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='bancas_al_primero',
            field=models.PositiveIntegerField(default=0, help_text="En algunos casos (concejales) se hace un D'Hont pero se garantizan N bancas al primero"),
        ),
        migrations.AddField(
            model_name='eleccion',
            name='bancas_dhont',
            field=models.PositiveIntegerField(default=44, help_text='Cantidad de bancas a repartir'),
        ),
        migrations.AddField(
            model_name='eleccion',
            name='mostrar_dhont',
            field=models.BooleanField(default=False, help_text="Mostrar distribucion de D'hont en resultados"),
        ),
    ]
