# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0009_auto_20190505_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaEleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmada', models.BooleanField(default=False)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Eleccion')),
            ],
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='eleccion',
        ),
        migrations.AddField(
            model_name='mesa',
            name='eleccion',
            field=models.ManyToManyField(through='elecciones.MesaEleccion', to='elecciones.Eleccion'),
        ),
        migrations.AddField(
            model_name='mesaeleccion',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Mesa'),
        ),
        migrations.AlterUniqueTogether(
            name='mesaeleccion',
            unique_together=set([('mesa', 'eleccion')]),
        ),
    ]
