# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0010_auto_20190507_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='nombre_corto',
            field=models.CharField(default='', max_length=20),
        ),
    ]
