# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0011_mesa_cargadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='confirmadas',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
