# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-07 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0012_mesa_confirmadas'),
        ('elecciones', '0011_auto_20190507_1338'),
    ]

    operations = [
    ]
