# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-09 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0013_merge_20190507_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuito',
            name='seccion_de_ponderacion',
        ),
        migrations.DeleteModel(
            name='AgrupacionPK',
        ),
    ]
