# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-09 19:37
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Sum


def calcular_electores(apps, schema_editor):
    Seccion = apps.get_model("elecciones", "Seccion")
    Mesa = apps.get_model("elecciones", "Mesa")
    for seccion in Seccion.objects.all():
        seccion.electores = Mesa.objects.filter(
            lugar_votacion__circuito__seccion=seccion,
        ).aggregate(v=Sum('electores'))['v']
        seccion.save(update_fields=['electores'])


def reverse_calcular_electores(apps, schema_editor):
    Seccion = apps.get_model("elecciones", "Seccion")
    Seccion.objects.all().update(electores=0)



class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0013_merge_20190507_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='electores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(calcular_electores, reverse_calcular_electores),
    ]
