# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-09 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0014_auto_20190509_0338'),
        ('elecciones', '0014_seccion_electores'),
    ]

    operations = [
    ]
