# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-11 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0015_merge_20190509_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='proyeccion_ponderada',
            field=models.BooleanField(default=False, help_text='Si está marcado, el cálculo de proyeccion se agrupará por circuitos para esta sección'),
        ),
    ]
