# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0016_seccion_proyeccion_ponderada'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si no está activa, no se cargan datos para esta eleccion y no se muestran resultados'),
        ),
    ]
