# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-11 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0017_eleccion_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='es_metadata',
            field=models.BooleanField(default=False, help_text="para campos que son tipo 'Total positivo, o Total votos'"),
        ),
    ]
