# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-12 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0018_opcion_es_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleccion',
            options={'ordering': ('id',), 'verbose_name': 'Elección', 'verbose_name_plural': 'Elecciones'},
        ),
        migrations.AddField(
            model_name='circuito',
            name='electores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
