# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-12 02:52
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Sum


def calcular_electores(apps, schema_editor):
    Circuito = apps.get_model("elecciones", "Circuito")
    Mesa = apps.get_model("elecciones", "Mesa")
    for circuito in Circuito.objects.all():
        circuito.electores = Mesa.objects.filter(
            lugar_votacion__circuito=circuito,
        ).aggregate(v=Sum('electores'))['v']
        circuito.save(update_fields=['electores'])


def reverse_calcular_electores(apps, schema_editor):
    Circuito = apps.get_model("elecciones", "Circuito")
    Circuito.objects.all().update(electores=0)


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0018_opcion_es_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleccion',
            options={'ordering': ('id',), 'verbose_name': 'Elección', 'verbose_name_plural': 'Elecciones'},
        ),
        migrations.AddField(
            model_name='circuito',
            name='electores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(calcular_electores, reverse_calcular_electores),
    ]
