# Generated by Django 2.2.1 on 2019-06-02 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0019_auto_20190511_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.Circuito'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones', to='elecciones.Partido'),
        ),
        migrations.AlterField(
            model_name='votomesareportado',
            name='fiscal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.Fiscal'),
        ),
    ]
