# Generated by Django 2.2.1 on 2019-06-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0020_auto_20190602_0009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eleccion',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='MesaEleccion',
            new_name='MesaCategoria',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('id',), 'verbose_name': 'Elección', 'verbose_name_plural': 'Categoriaes'},
        ),
    ]
