# Generated by Django 2.2.1 on 2019-06-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0021_auto_20190630_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('id',), 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='eleccion',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='mesacategoria',
            old_name='eleccion',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='votomesareportado',
            old_name='eleccion',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si no está activa, no se cargan datos para esta categoria y no se muestran resultados'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='opciones',
            field=models.ManyToManyField(related_name='categorias', to='elecciones.Opcion'),
        ),
        migrations.AlterUniqueTogether(
            name='mesacategoria',
            unique_together={('mesa', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            unique_together={('mesa', 'categoria', 'opcion')},
        ),
    ]
