# Generated by Django 2.2.1 on 2019-07-01 02:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields



def crear_y_asignar_carga(apps, schema_editor):
    Carga = apps.get_model("elecciones", "Carga")
    VotoMesaReportado = apps.get_model("elecciones", "VotoMesaReportado")
    for vmr in VotoMesaReportado.objects.all():
        c, _ = Carga.objects.get_or_create(
            mesa=vmr.mesa, categoria=vmr.categoria, fiscal=vmr.fiscal,
            defaults={'created': vmr.created, 'modified': vmr.modified},
        )
        vmr.carga = c
        vmr.save(update_fields=['carga'])


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0002_auto_20190504_1938'),
        ('elecciones', '0023_auto_20190630_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('consolidada', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Categoria')),
                ('fiscal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.Fiscal')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Mesa')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
            },
        ),
        migrations.AddField(
            model_name='votomesareportado',
            name='carga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Carga'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            unique_together={('carga', 'opcion')},
        ),
        migrations.RunPython(crear_y_asignar_carga),
        migrations.RemoveField(
            model_name='votomesareportado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='votomesareportado',
            name='created',
        ),
        migrations.RemoveField(
            model_name='votomesareportado',
            name='fiscal',
        ),
        migrations.RemoveField(
            model_name='votomesareportado',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='votomesareportado',
            name='modified',
        ),
    ]
