# Generated by Django 2.2.1 on 2019-07-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0024_auto_20190630_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='black', help_text='Color para css (Ej: red o #FF0000)', max_length=10),
        ),
    ]
