# Generated by Django 2.2.1 on 2019-07-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0026_auto_20190706_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ('numero',), 'verbose_name': 'Sección electoral', 'verbose_name_plural': 'Secciones electorales'},
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='elecciones.Distrito'),
        ),
    ]
