# Generated by Django 2.2.1 on 2019-07-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0005_auto_20190707_2345'),
        ('elecciones', '0027_auto_20190707_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='hora_escrutada',
        ),
        migrations.AddField(
            model_name='mesa',
            name='attachments',
            field=models.ManyToManyField(through='adjuntos.Identificacion', to='adjuntos.Attachment'),
        ),
    ]
