# Generated by Django 2.2.1 on 2019-07-11 14:42

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0027_auto_20190710_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carga',
            options={},
        ),
        migrations.RemoveField(
            model_name='carga',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='carga',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='carga_confirmada',
        ),
        migrations.RemoveField(
            model_name='mesacategoria',
            name='confirmada',
        ),
        migrations.AddField(
            model_name='carga',
            name='firma',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carga',
            name='mesa_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='elecciones.MesaCategoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carga',
            name='origen',
            field=models.CharField(choices=[('web', 'web'), ('csv', 'csv'), ('telegram', 'telegram')], default='web', max_length=50),
        ),
        migrations.AddField(
            model_name='carga',
            name='status',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='falta_foto', max_length=100, no_check_for_status=True, null=True),
        ),
        migrations.AddField(
            model_name='mesacategoria',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='sin_cargar', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='votomesareportado',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportados', to='elecciones.Carga'),
        ),
    ]
