# Generated by Django 2.2.1 on 2019-07-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0028_auto_20190707_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
