# Generated by Django 2.2.1 on 2019-07-13 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0028_auto_20190711_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaOpcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritaria', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Categoria')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Opcion'))

            ],
        ),
        migrations.RemoveField(
            model_name='carga',
            name='consolidada',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='obligatorio',
        ),
        migrations.AddField(
            model_name='mesacategoria',
            name='carga_testigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_testigo', to='elecciones.Carga'),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='opciones',
        ),
        migrations.AddField(
            model_name='categoria',
            name='opciones',
            field=models.ManyToManyField(related_name='categorias', through='elecciones.CategoriaOpcion', to='elecciones.Opcion'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaopcion',
            unique_together={('categoria', 'opcion')},
        ),
    ]
