# Generated by Django 2.2.2 on 2019-07-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0028_auto_20190707_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'Distrito electoral', 'verbose_name_plural': 'Distritos electorales'},
        ),
        migrations.AlterModelOptions(
            name='eleccion',
            options={'verbose_name': 'Elección', 'verbose_name_plural': 'Elecciones'},
        ),
        migrations.AlterModelOptions(
            name='mesacategoria',
            options={'verbose_name': 'Mesa categoría', 'verbose_name_plural': 'Mesas Categorías'},
        ),
    ]
