# Generated by Django 2.2.1 on 2019-07-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0028_auto_20190711_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesacategoria',
            name='carga_testigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_testigo', to='elecciones.Carga'),
        ),
    ]
