# Generated by Django 2.2.1 on 2019-07-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0029_auto_20190709_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='attachments',
        ),
    ]
