# Generated by Django 2.2.1 on 2019-07-16 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0029_auto_20190712_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carga',
            old_name='status',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='carga',
            name='valida',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='NovedadesCarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='elecciones.Carga')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
