# Generated by Django 2.2.1 on 2019-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0029_auto_20190712_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga',
            name='status',
        ),
        migrations.AddField(
            model_name='carga',
            name='procesada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carga',
            name='tipo',
            field=models.CharField(blank=True, choices=[('falta_foto', 'falta_foto'), ('parcial', 'parcial'), ('total', 'total')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carga',
            name='valida',
            field=models.BooleanField(default=True),
        ),
    ]
