# Generated by Django 2.2.2 on 2019-07-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0030_auto_20190716_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='cargadas',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='confirmadas',
        ),
    ]
