# Generated by Django 2.2.2 on 2019-07-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0031_auto_20190716_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'Distrito electoral', 'verbose_name_plural': 'Distritos electorales'},
        ),
        migrations.AlterModelOptions(
            name='mesacategoria',
            options={'verbose_name': 'Mesa categoría', 'verbose_name_plural': 'Mesas Categorías'},
        ),
    ]
