# Generated by Django 2.2.2 on 2019-07-18 21:46

import django.core.validators
from django.db import migrations, models
import model_utils.fields


def update_status(apps, schema_editor):
    MesaCategoria = apps.get_model("elecciones", "MesaCategoria")
    MesaCategoria.objects.filter(status='sin_cargar').update(status='00_sin_cargar')


def revert_status(apps, schema_editor):
    MesaCategoria = apps.get_model("elecciones", "MesaCategoria")
    MesaCategoria.objects.filter(status='00_sin_cargar').update(status='sin_cargar')


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0032_auto_20190717_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='orden_de_carga',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='taken',
        ),
        migrations.AddField(
            model_name='categoria',
            name='prioridad',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='categoria',
            name='requiere_cargas_parciales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circuito',
            name='prioridad',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='distrito',
            name='prioridad',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='mesa',
            name='prioridad',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='mesacategoria',
            name='orden_de_carga',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesacategoria',
            name='taken',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='seccion',
            name='prioridad',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='mesacategoria',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='00_sin_cargar', max_length=100, no_check_for_status=True),
        ),
        migrations.RunPython(update_status, revert_status),
    ]
