# Generated by Django 2.2.2 on 2019-07-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0032_auto_20190717_1917'),
        ('elecciones', '0032_opcion_codigo'),
    ]

    operations = [
    ]
