# Generated by Django 2.2.2 on 2019-07-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0033_auto_20190718_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga',
            name='valida',
        ),
        migrations.AddField(
            model_name='carga',
            name='invalidada',
            field=models.BooleanField(default=False),
        ),
    ]
