# Generated by Django 2.2.2 on 2019-07-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0033_auto_20190718_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga',
            name='valida',
        ),
        migrations.AddField(
            model_name='carga',
            name='invalidada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carga',
            name='tipo',
            field=models.CharField(blank=True, choices=[('problema', 'problema'), ('parcial', 'parcial'), ('total', 'total')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si no está activa, no se cargan datos para esta categoría y no se muestran resultados'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='back_color',
            field=models.CharField(default='white', help_text='Color para CSS (ej, red o #FF0000)', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='black', help_text='Color para CSS (ej, red o #FF0000)', max_length=10),
        ),
    ]
