# Generated by Django 2.2.2 on 2019-07-22 01:11

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0033_auto_20190718_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga',
            name='valida',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='es_contable',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='es_metadata',
        ),
        migrations.AddField(
            model_name='carga',
            name='invalidada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opcion',
            name='tipo',
            field=models.CharField(choices=[('positivo', 'positivo'), ('no_positivo', 'no_positivo'), ('metadata', 'metadata')], default='positivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='carga',
            name='tipo',
            field=models.CharField(blank=True, choices=[('problema', 'problema'), ('parcial', 'parcial'), ('total', 'total')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si no está activa, no se cargan datos para esta categoría y no se muestran resultados.'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='back_color',
            field=models.CharField(default='white', help_text='Color para CSS (ej, red o #FF0000)', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='black', help_text='Color para CSS (ej, red o #FF0000)', max_length=10),
        ),
        migrations.AlterField(
            model_name='lugarvotacion',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
