# Generated by Django 2.2.2 on 2019-07-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0033_auto_20190718_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='es_contable',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='es_metadata',
        ),
        migrations.AddField(
            model_name='opcion',
            name='tipo',
            field=models.CharField(choices=[('positivo', 'positivo'), ('no_positivo', 'no_positivo'), ('metadata', 'metadata')], default='positivo', max_length=100),
        ),
    ]
