# Generated by Django 2.2.2 on 2019-07-21 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0034_auto_20190719_1743'),
        ('elecciones', '0034_auto_20190721_1032'),
    ]

    operations = [
    ]
