# Generated by Django 2.2.2 on 2019-07-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0034_auto_20190721_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscales.Fiscal'),
        ),
    ]
