# Generated by Django 2.2.2 on 2019-07-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0035_opcion_codigo'),
        ('elecciones', '0035_auto_20190722_1001'),
    ]

    operations = [
    ]
