# Generated by Django 2.2.2 on 2019-07-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0035_opcion_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaopcion',
            options={'ordering': ['categoria'], 'verbose_name': 'Categoría opción', 'verbose_name_plural': 'Categorías opciones'},
        ),
        migrations.CreateModel(
            name='SeccionPolitica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones_politicas', to='elecciones.Distrito')),
            ],
            options={
                'verbose_name': 'Sección política',
                'verbose_name_plural': 'Secciones políticas',
                'ordering': ('numero',),
            },
        ),
        migrations.AddField(
            model_name='seccion',
            name='seccion_politica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='elecciones.SeccionPolitica'),
        ),
    ]
