# Generated by Django 2.2.2 on 2019-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0036_auto_20190722_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaopcion',
            options={'ordering': ['categoria'], 'verbose_name': 'Asociación Categoría-Opción', 'verbose_name_plural': 'Asociaciones Categoría-Opción'},
        ),
        migrations.AlterField(
            model_name='carga',
            name='tipo',
            field=models.CharField(choices=[('problema', 'problema'), ('parcial', 'parcial'), ('total', 'total')], default='parcial', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votomesareportado',
            name='votos',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
