# Generated by Django 2.2.2 on 2019-07-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0036_merge_20190722_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaopcion',
            options={'verbose_name': 'Asociación Categoría-Opción', 'verbose_name_plural': 'Asociaciones Categoría-Opción'},
        ),
        migrations.AlterField(
            model_name='carga',
            name='tipo',
            field=models.CharField(choices=[('problema', 'problema'), ('parcial', 'parcial'), ('total', 'total')], default='problema', max_length=50),
            preserve_default=False,
        ),
    ]
