# Generated by Django 2.2.2 on 2019-07-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0037_auto_20190723_1006'),
        ('elecciones', '0036_auto_20190722_1610'),
    ]

    operations = [
    ]
