# Generated by Django 2.2.2 on 2019-07-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0038_merge_20190723_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaopcion',
            options={'ordering': ['categoria'], 'verbose_name': 'Asociación Categoría-Opción', 'verbose_name_plural': 'Asociaciones Categoría-Opción'},
        ),
    ]
