# Generated by Django 2.2.2 on 2019-07-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0038_merge_20190723_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaopcion',
            options={'ordering': ['categoria'], 'verbose_name': 'Asociación Categoría-Opción', 'verbose_name_plural': 'Asociaciones Categoría-Opción'},
        ),
        migrations.CreateModel(
            name='PrioridadScheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.PositiveIntegerField()),
                ('hasta', models.PositiveIntegerField()),
                ('prioridad', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioridades', to='elecciones.Categoria')),
                ('circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioridades', to='elecciones.Circuito')),
            ],
        ),
    ]
