# Generated by Django 2.2.2 on 2019-07-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0036_merge_20190722_2250'),
        ('elecciones', '0038_merge_20190723_1146'),
    ]

    operations = [
    ]
