# Generated by Django 2.2.2 on 2019-07-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0039_merge_20190723_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaopcion',
            options={'ordering': ['categoria'], 'verbose_name': 'Asociación Categoría-Opción', 'verbose_name_plural': 'Asociaciones Categoría-Opción'},
        ),
    ]
