# Generated by Django 2.2.2 on 2019-07-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0039_auto_20190729_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrupacionCircuito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaProyeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Técnica de Proyección',
                'verbose_name_plural': 'Técnicas de Proyección',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='AgrupacionCircuitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('minimo_mesas', models.PositiveIntegerField(default=1)),
                ('circuitos', models.ManyToManyField(related_name='agrupaciones', through='elecciones.AgrupacionCircuito', to='elecciones.Circuito')),
                ('proyeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupaciones', to='elecciones.TecnicaProyeccion')),
            ],
            options={
                'verbose_name': 'Agrupación de Circuitos',
                'verbose_name_plural': 'Agrupaciones de Cicuitos',
            },
        ),
        migrations.AddField(
            model_name='agrupacioncircuito',
            name='agrupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.AgrupacionCircuitos'),
        ),
        migrations.AddField(
            model_name='agrupacioncircuito',
            name='circuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Circuito'),
        ),
    ]
