# Generated by Django 2.2.2 on 2019-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0040_auto_20190724_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votomesareportado',
            name='votos',
            field=models.PositiveIntegerField(),
        ),
    ]
