# Generated by Django 2.2.2 on 2019-07-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0040_agrupacioncircuitos_tecnicaproyeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrupacioncircuitos',
            name='opciones',
            field=models.ManyToManyField(to='elecciones.Circuito'),
        ),
    ]
