# Generated by Django 2.2.2 on 2019-07-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0040_auto_20190730_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sensible',
            field=models.BooleanField(default=False, help_text='Solo pueden visualizar los resultados de esta cagtegoría con permisos especiales.'),
        ),
    ]
