# Generated by Django 2.2.2 on 2019-08-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0041_categoria_sensible'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarvotacion',
            name='numero',
            field=models.CharField(blank=True, help_text='Número de escuela', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='numero',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuitos', to='elecciones.Seccion'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='numero',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lugarvotacion',
            name='circuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares_votacion', to='elecciones.Circuito'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Codigo de opción', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Codigo de partido', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='numero',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
