# Generated by Django 2.2.2 on 2019-08-02 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0041_categoria_sensible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuitos', to='elecciones.Seccion'),
        ),
        migrations.AlterField(
            model_name='lugarvotacion',
            name='circuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares_votacion', to='elecciones.Circuito'),
        ),
    ]
