# Generated by Django 2.2.2 on 2019-07-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0041_agrupacioncircuitos_opciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agrupacioncircuitos',
            old_name='opciones',
            new_name='circuitos',
        ),
    ]
