# Generated by Django 2.2.2 on 2019-08-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0042_auto_20190802_2059'),
        ('elecciones', '0042_indice_cod_y_nro_escuela'),
    ]

    operations = [
    ]
