# Generated by Django 2.2.2 on 2019-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0042_auto_20190727_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupacioncircuitos',
            name='circuitos',
            field=models.ManyToManyField(related_name='agrupaciones', to='elecciones.Circuito'),
        ),
    ]
