# Generated by Django 2.2.2 on 2019-08-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0043_merge_20190803_0725'),
        ('elecciones', '0041_auto_20190801_2211'),
    ]

    operations = [
    ]
