# Generated by Django 2.2.2 on 2019-08-05 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0044_merge_20190803_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='elecciones.Circuito'),
        ),
    ]
