# Generated by Django 2.2.2 on 2019-08-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0045_auto_20190804_2322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('circuito', 'numero')},
        ),
    ]
