# Generated by Django 2.2.2 on 2019-08-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0045_auto_20190804_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='proyeccion_ponderada',
        ),
    ]
