# Generated by Django 2.2.2 on 2019-08-06 03:24

from django.db import migrations
from collections import Counter


def sanear(apps, schema_editor):
    Mesa = apps.get_model("elecciones", "Mesa")
    problemas = [
        c for c in Counter(
            Mesa.objects.values_list('circuito', 'numero')
        ).most_common() if c[1] > 1
    ]
    for prob in problemas:
        circuito_id, n = prob[0]
        mesas = Mesa.objects.filter(circuito__id=circuito_id, numero=n)
        primera = mesas[0].id
        print(f'Conflictos circuito_id={circuito_id} numero={n}: {[m.id for m in mesas]}. Queda {primera}.')
        mesas.exclude(id=primera).delete()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('elecciones', '0046_remove_seccion_proyeccion_ponderada'),
    ]

    operations = [
        migrations.RunPython(sanear, atomic=True),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('circuito', 'numero')},
        ),
    ]
