# Generated by Django 2.2.2 on 2019-08-06 02:00
import re
from django.db import migrations
import model_utils.fields


def update_status(apps, schema_editor):
    MesaCategoria = apps.get_model("elecciones", "MesaCategoria")
    pattern = re.compile(r'^\d{2}_(.*)')
    for mc in MesaCategoria.objects.all():
        mc.status = re.sub(pattern, r'\1', mc.status)
        mc.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0046_remove_seccion_proyeccion_ponderada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesacategoria',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='sin_cargar', max_length=100, no_check_for_status=True),
        ),
        migrations.RunPython(update_status),
    ]
