# Generated by Django 2.2.2 on 2019-08-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0047_auto_20190806_0024'),
        ('elecciones', '0047_auto_20190805_2300'),
    ]

    operations = [
    ]
