# Generated by Django 2.2.2 on 2019-08-06 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0007_merge_20190804_1240'),
        ('elecciones', '0047_auto_20190805_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionComputo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_computo', to='fiscales.Fiscal')),
            ],
            options={
                'verbose_name': 'Configuración para cómputo',
                'verbose_name_plural': 'Configuraciones para cómputo',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionComputoDistrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregacion', models.CharField(choices=[('todas_las_cargas', 'Todas'), ('solo_consolidados', 'Consolidadas'), ('solo_consolidados_doble_carga', 'Consolidadas con doble Carga')], max_length=20)),
                ('opciones', models.CharField(choices=[('prioritarias', 'prioritarias'), ('todas', 'todas')], max_length=20)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.ConfiguracionComputo')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Distrito')),
                ('proyeccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.TecnicaProyeccion')),
            ],
            options={
                'verbose_name': 'Configuración para cómputo por distrito',
                'verbose_name_plural': 'Configuraciones para cómputo por distrito',
            },
        ),
    ]
