# Generated by Django 2.2.2 on 2019-08-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0048_configuracioncomputo_configuracioncomputodistrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncomputodistrito',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='elecciones.ConfiguracionComputo'),
        ),
    ]
