# Generated by Django 2.2.2 on 2019-08-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0049_auto_20190806_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncomputodistrito',
            name='agregacion',
            field=models.CharField(choices=[('todas_las_cargas', 'Todas'), ('solo_consolidados', 'Consolidadas'), ('solo_consolidados_doble_carga', 'Consolidadas con doble Carga')], max_length=30),
        ),
        migrations.AlterField(
            model_name='configuracioncomputodistrito',
            name='opciones',
            field=models.CharField(choices=[('prioritarias', 'Prioritarias'), ('todas', 'Todas')], max_length=30),
        ),
    ]
