# Generated by Django 2.2.2 on 2019-08-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0048_merge_20190806_1712'),
        ('elecciones', '0050_auto_20190806_2310'),
    ]

    operations = [
    ]
