# Generated by Django 2.2.2 on 2019-08-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0051_merge_20190807_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncomputodistrito',
            name='proyeccion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.TecnicaProyeccion'),
        ),
        migrations.AddConstraint(
            model_name='configuracioncomputo',
            constraint=models.UniqueConstraint(fields=('nombre',), name='nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='configuracioncomputodistrito',
            constraint=models.UniqueConstraint(fields=('configuracion', 'distrito'), name='distrito_unico'),
        ),
    ]
