# Generated by Django 2.2.2 on 2019-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0052_auto_20190809_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='extranjeros',
            field=models.BooleanField(default=False),
        ),
    ]
