# Generated by Django 2.2.2 on 2019-08-10 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0052_auto_20190809_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='extranjeros',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='lugar_votacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='elecciones.LugarVotacion', verbose_name='Lugar de votacion'),
        ),
    ]
