# Generated by Django 2.2.2 on 2019-08-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0053_auto_20190810_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaOficialControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultimo_registro', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='mesacategoria',
            name='carga_oficial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_oficial', to='elecciones.Carga'),
        ),
        migrations.AddField(
            model_name='mesacategoria',
            name='parcial_oficial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_parcial_oficial', to='elecciones.Carga'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='tipo',
            field=models.CharField(choices=[('problema', 'problema'), ('parcial', 'parcial'), ('total', 'total'), ('total_oficial', 'total_oficial'), ('parcial_oficial', 'parcial_oficial')], max_length=50),
        ),
    ]
