# Generated by Django 2.2.2 on 2019-08-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0053_mesa_extranjeros'),
        ('elecciones', '0053_auto_20190810_1932'),
    ]

    operations = [
    ]
