# Generated by Django 2.2.2 on 2019-08-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0054_auto_20190811_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaoficialcontrol',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Categoria'),
        ),
    ]
