# Generated by Django 2.2.2 on 2019-08-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0054_auto_20190811_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesacategoria',
            name='taken',
        ),
        migrations.RemoveField(
            model_name='mesacategoria',
            name='taken_by',
        ),
        migrations.AddField(
            model_name='mesacategoria',
            name='cant_fiscales_asignados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
