# Generated by Django 2.2.2 on 2019-08-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0055_reemplazo_taken'),
        ('elecciones', '0055_cargaoficialcontrol_categoria'),
    ]

    operations = [
    ]
