# Generated by Django 2.2.2 on 2019-09-01 15:04

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0056_merge_20190830_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto_ejemplo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='elecciones/categorias', width_field='width'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
    ]
