# Generated by Django 2.2.2 on 2019-09-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0058_limpieza_prioridades'),
        ('elecciones', '0058_auto_20190908_1857'),
    ]

    operations = [
    ]
