# Generated by Django 2.2.2 on 2019-09-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0059_merge_20190910_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Código de opción', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='tipo',
            field=models.CharField(choices=[('positivo', 'positivo'), ('no_positivo', 'no_positivo'), ('metadata', 'metadata'), ('metadata_optativa', 'metadata_optativa')], default='positivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='partido',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Código de partido', max_length=10, null=True),
        ),
    ]
