# Generated by Django 2.2.2 on 2019-09-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0060_metadata_optativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='tomada_por_consolidador',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
