# Generated by Django 2.2.2 on 2019-10-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0061_carga_tomada_por_consolidador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='nombre_corto',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='tipo',
            field=models.CharField(choices=[('positivo', 'positivo'), ('no_positivo', 'no_positivo'), ('metadata', 'metadata'), ('metadata_optativa', 'metadata_optativa')], db_index=True, default='positivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnicaproyeccion',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
