# Generated by Django 2.2.2 on 2019-10-18 23:01

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0062_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='tipo',
            field=models.CharField(choices=[('problema', 'problema'), ('parcial', 'parcial'), ('total', 'total'), ('total_oficial', 'total_oficial'), ('parcial_oficial', 'parcial_oficial')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mesacategoria',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default='sin_cargar', max_length=100, no_check_for_status=True),
        ),
    ]
