# Generated by Django 2.2.2 on 2019-10-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0062_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(db_index=True, default=True, help_text='Si no está activa, no se cargan datos para esta categoría y no se muestran resultados.'),
        ),
    ]
