# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimetype', models.CharField(max_length=100, null=True)),
                ('foto', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='attachments/', width_field='width')),
                ('foto_edited', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='attachments/edited', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('taken', models.DateTimeField(null=True)),
                ('problema', models.CharField(blank=True, choices=[('no es una foto válida', 'no es una foto válida'), ('no se entiende', 'no se entiende')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('from_address', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('title', models.CharField(max_length=150)),
                ('uid', models.PositiveIntegerField()),
                ('message_id', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adjuntos.Email'),
        ),
    ]
