# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adjuntos', '0001_initial'),
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='elecciones.Mesa'),
        ),
    ]
