# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-07 21:22
from __future__ import unicode_literals
from django.db import migrations, models
from adjuntos.models import hash_file


def calcular_digest(apps, schema_editor):
    Attachment = apps.get_model("adjuntos", "Attachment")
    for a in Attachment.objects.filter(foto__isnull=False):
        a.foto_digest = hash_file(a.foto.file.file)
        a.save(update_fields=['foto_digest'])


def reverse_calcular_digest(apps, schema_editor):
    Attachment = apps.get_model("adjuntos", "Attachment")
    Attachment.objects.all().update(foto_digest=None)


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0002_attachment_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='foto_digest',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunPython(calcular_digest, reverse_calcular_digest),
        migrations.AlterField(
            model_name='attachment',
            name='foto_digest',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
