# Generated by Django 2.2.1 on 2019-07-10 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0002_auto_20190504_1938'),
        ('elecciones', '0027_auto_20190710_1356'),
        ('adjuntos', '0004_auto_20190602_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='problema',
        ),
        migrations.AddField(
            model_name='attachment',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='sin_identificar', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='elecciones.Mesa'),
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('identificada', 'identificada'), ('spam', 'Es SPAM'), ('invalida', 'Es inválida')], default='identificada', max_length=100, no_check_for_status=True)),
                ('consolidada', models.BooleanField(default=False, help_text='una identificacion consolidada es aquella que se considera representativa y determina el estado del attachment')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificaciones', to='adjuntos.Attachment')),
                ('fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.Fiscal')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.Mesa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
