# Generated by Django 2.2.1 on 2019-07-08 02:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0002_auto_20190504_1938'),
        ('elecciones', '0027_auto_20190707_1308'),
        ('adjuntos', '0004_auto_20190602_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='mesa',
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('agregada', 'agregada'), ('consolidada', 'consolidada')], default='agregada', max_length=100, no_check_for_status=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjuntos.Attachment')),
                ('fiscal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.Fiscal')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.Mesa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
