# Generated by Django 2.2.2 on 2019-07-14 23:17

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0005_auto_20190710_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacion',
            name='source',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='web', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='consolidada',
            field=models.BooleanField(default=False, help_text='Una identificación consolidada es aquella que se considera representativa y determina el estado del attachment'),
        ),
    ]
