# Generated by Django 2.2.1 on 2019-07-16 16:01

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0005_auto_20190710_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificacion',
            name='consolidada',
        ),
        migrations.AddField(
            model_name='attachment',
            name='identificacion_testigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_testigo', to='adjuntos.Identificacion'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='procesada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='source',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='web', max_length=100, no_check_for_status=True),
        ),
    ]
