# Generated by Django 2.2.2 on 2019-07-15 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0006_auto_20190714_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadesIdentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjuntos.Identificacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
