# Generated by Django 2.2.1 on 2019-07-09 17:34

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0007_auto_20190709_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacion',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='identificada', max_length=100, no_check_for_status=True),
        ),
    ]
