# Generated by Django 2.2.2 on 2019-07-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0007_identificacion_invalidada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adjuntos.Email'),
        ),
    ]
