# Generated by Django 2.2.2 on 2019-07-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0007_identificacion_invalidada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacion',
            name='fiscal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fiscales.Fiscal'),
        ),
    ]
