# Generated by Django 2.2.2 on 2019-07-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0008_identificacion_parcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacionparcial',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Distrito'),
        ),
    ]
