# Generated by Django 2.2.2 on 2019-07-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0008_auto_20190721_1529'),
        ('adjuntos', '0008_auto_20190726_0223'),
    ]

    operations = [
    ]
