# Generated by Django 2.2.1 on 2019-07-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0008_auto_20190709_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='problema',
        ),
    ]
