# Generated by Django 2.2.1 on 2019-07-10 12:10

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0009_remove_attachment_problema'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='sin_identificar', max_length=100, no_check_for_status=True),
        ),
    ]
