# Generated by Django 2.2.2 on 2019-07-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0009_merge_20190727_1124'),
    ]

    operations = [
    ]
