# Generated by Django 2.2.1 on 2019-07-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0030_remove_mesa_attachments'),
        ('adjuntos', '0010_attachment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='elecciones.Mesa'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecciones.Mesa'),
        ),
    ]
