# Generated by Django 2.2.2 on 2019-07-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0010_merge_20190729_0913'),
        ('adjuntos', '0009_auto_20190726_1009'),
    ]

    operations = [
    ]
