# Generated by Django 2.2.2 on 2019-07-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0005_auto_20190728_0139'),
        ('elecciones', '0037_auto_20190727_1136'),
        ('adjuntos', '0011_merge_20190729_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdentificacionParcial',
            new_name='PreIdentificacion',
        ),
    ]
