# Generated by Django 2.2.2 on 2019-08-05 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0012_pre_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacion',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identificaciones', to='elecciones.Mesa'),
        ),
    ]
