# Generated by Django 2.2.2 on 2019-09-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0015_identificacion_tomada_por_consolidador'),
        ('adjuntos', '0015_csvtareadeimportacion'),
    ]

    operations = [
    ]
