# Generated by Django 2.2.2 on 2019-10-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0016_csvtareadeimportacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
