# Generated by Django 2.2.2 on 2021-05-23 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0017_auto_20191025_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adjuntos.Attachment'),
        ),
    ]
