# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='problema',
            field=models.CharField(blank=True, choices=[('Error de carga en Gobernador', 'Error de carga en Gobernador'), ('Error de carga en Legisladores', 'Error de carga en Legisladores'), ('Error de carga en IntendenteFoto/s no válidas', 'Error de carga en IntendenteFoto/s no válidas'), ('Total incorrecto', 'Total incorrecto'), ('Otro', 'Otro')], max_length=100, null=True),
        ),
    ]
