# Generated by Django 2.2.1 on 2019-06-02 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0002_auto_20190511_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='resuelto_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
