# Generated by Django 2.2.2 on 2019-07-19 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0003_auto_20190719_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='adjuntos.Attachment'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='elecciones.Mesa'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportedeproblema',
            name='tipo_de_problema',
            field=models.CharField(blank=True, choices=[('spam', 'Es SPAM'), ('invalida', 'Es inválida'), ('ilegible', 'No se entiende'), ('falta_foto', 'La parte que es necesario cargar no está entre las fotos presentes')], max_length=100, null=True),
        ),
    ]
