# Generated by Django 2.2.2 on 2019-07-22 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0003_auto_20190719_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='adjuntos.Attachment'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='estado',
            field=models.CharField(blank=True, choices=[('potencial', 'potencial'), ('descartado', 'descartado'), ('pendiente', 'pendiente'), ('en_curso', 'en curso'), ('resuelto', 'resuelto')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problema',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='elecciones.Mesa'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportedeproblema',
            name='carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='elecciones.Carga'),
        ),
        migrations.AlterField(
            model_name='reportedeproblema',
            name='identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='adjuntos.Identificacion'),
        ),
        migrations.AlterField(
            model_name='reportedeproblema',
            name='tipo_de_problema',
            field=models.CharField(choices=[('spam', 'La foto no es ni de un acta ni de un certificado. Parece subida maliciosamente.'), ('invalida', 'Falla alguna validación del sistema que no debería fallar.'), ('ilegible', 'La foto es de un acta pero no la puedo leer con claridad.'), ('falta_foto', 'La parte que es necesario cargar no está entre las fotos presentes.')], default='ilegible', max_length=100, null=True),
        ),
    ]
