# Generated by Django 2.2.2 on 2019-07-19 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adjuntos', '0007_identificacion_invalidada'),
        ('fiscales', '0003_fiscal_troll'),
        ('elecciones', '0034_auto_20190719_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoScoringTroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('motivo', model_utils.fields.StatusField(choices=[('carga_valores_distintos_a_confirmados', 'Carga valores distintos a los confirmados'), ('identificacion_attachment_distinta_a_confirmada', 'Identifica un attachment de una forma distinta a la confirmada'), ('remocion_marca_troll', 'Se remueve la marca de troll a un fiscal')], default='carga_valores_distintos_a_confirmados', max_length=100, no_check_for_status=True)),
                ('automatico', models.BooleanField(default=True)),
                ('variacion', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.Fiscal')),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adjuntos.Attachment')),
                ('fiscal_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_scoring_troll', to='fiscales.Fiscal')),
                ('mesa_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.MesaCategoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CambioEstadoTroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('automatico', models.BooleanField(default=True)),
                ('troll', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscales.Fiscal')),
                ('evento_disparador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antitrolling.EventoScoringTroll')),
                ('fiscal_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado_troll', to='fiscales.Fiscal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
