# Generated by Django 2.2.2 on 2019-07-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antitrolling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoscoringtroll',
            name='motivo',
            field=models.CharField(choices=[('carga_valores_distintos_a_confirmados', 'Carga valores distintos a los confirmados'), ('indica_problema_mesa_categoria_confirmada', 'Indica "problema" para una mesa/categoría con carga confirmada'), ('identificacion_attachment_distinta_a_confirmada', 'Identifica un attachment de una forma distinta a la confirmada'), ('marca_explicita_troll', 'Un usuario marca explitimamente a un fiscal como troll'), ('remocion_marca_troll', 'Se remueve la marca de troll a un fiscal')], max_length=50),
        ),
    ]
