# Generated by Django 2.2.2 on 2019-07-27 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0037_auto_20190727_1136'),
        ('antitrolling', '0002_auto_20190724_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoscoringtroll',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Mesa'),
        ),
        migrations.AlterField(
            model_name='eventoscoringtroll',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adjuntos.Attachment'),
        ),
        migrations.AlterField(
            model_name='eventoscoringtroll',
            name='mesa_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.MesaCategoria'),
        ),
        migrations.AlterField(
            model_name='eventoscoringtroll',
            name='motivo',
            field=models.CharField(choices=[('carga_valores_distintos_a_confirmados', 'Carga valores distintos a los confirmados'), ('indica_problema_mesa_categoria_confirmada', 'Indica "problema" para una mesa/categoría con carga confirmada'), ('identificacion_attachment_distinta_a_confirmada', 'Identifica un attachment de una forma distinta a la confirmada'), ('problema_descartado', 'Se descarta un "problema" reportado por el usuario.'), ('marca_explicita_troll', 'Un usuario marca explitimamente a un fiscal como troll'), ('remocion_marca_troll', 'Se remueve la marca de troll a un fiscal')], max_length=50),
        ),
    ]
