# Generated by Django 2.2.2 on 2019-09-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antitrolling', '0003_descartar_problema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoscoringtroll',
            name='motivo',
            field=models.CharField(choices=[('carga_valores_distintos_a_confirmados', 'Carga valores distintos a los confirmados'), ('indica_problema_mesa_categoria_confirmada', 'Indica "problema" para una mesa/categoría con carga confirmada'), ('identificacion_attachment_distinta_a_confirmada', 'Identifica un attachment de una forma distinta a la confirmada'), ('problema_descartado', 'Se descarta un "problema" reportado por el usuario.'), ('marca_explicita_troll', 'Un usuario marca explitimamente a un fiscal como troll'), ('remocion_marca_troll', 'Se remueve la marca de troll a un fiscal'), ('carga_aceptada', 'Carga los valores aceptados'), ('identificacion_aceptada', 'Realiza una identificación con la decisión aceptada')], max_length=50),
        ),
    ]
